import { Product } from '../types';

export function normalizeProduct(p: any): Product {
  if (!p) {
    return {
      id: 'prod_' + Math.random().toString(36).substring(2, 9),
      title: 'Produto Sem Nome',
      price: 0,
      currency: 'XOF',
      installmentsMax: 1,
      installmentsInterestFree: true,
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
      galleryImages: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
      category: 'Geral',
      categorySlug: 'geral',
      condition: 'novo',
      brand: 'Nusali',
      model: '',
      rating: 4.8,
      reviewsCount: 1,
      seller: {
        id: 'store_001',
        name: 'Vendedor Oficial Mercado Nusali',
        reputationLevel: 'platinum',
        reputationScore: 5.0,
        salesCount: 100,
        location: { city: 'Bissau', state: 'Setor Autónomo' },
        goodService: true,
        onTimeDelivery: true,
      },
      shipping: {
        freeShipping: true,
        arrivesTomorrow: true,
        shippingPrice: 0,
        fullFulfilled: true,
        originCountry: 'GW',
      },
      stock: 10,
      salesCount: 10,
      description: '',
      specs: {},
      questions: [],
      reviews: [],
    };
  }

  const rawPrice = typeof p.price === 'number' ? p.price : parseFloat(p.price) || 0;

  return {
    id: String(p.id || 'prod_' + Math.random().toString(36).substring(2, 9)),
    title: String(p.title || p.name || 'Produto Mercado Nusali'),
    price: rawPrice,
    currency: p.currency || 'XOF',
    originalPrice: p.originalPrice ? Number(p.originalPrice) : undefined,
    discountPercentage: p.discountPercentage ? Number(p.discountPercentage) : undefined,
    installmentsMax: Number(p.installmentsMax) || 6,
    installmentsInterestFree: p.installmentsInterestFree !== false,
    image: p.image || p.imageUrl || 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    galleryImages: Array.isArray(p.galleryImages) && p.galleryImages.length > 0
      ? p.galleryImages
      : [p.image || p.imageUrl || 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
    videos: Array.isArray(p.videos)
      ? p.videos
      : (p.videoUrl ? [{ url: p.videoUrl, title: 'Vídeo Demonstrativo', duration: '0:30', type: 'mp4' }] : []),
    videoUrl: p.videoUrl || (Array.isArray(p.videos) && p.videos[0] ? (typeof p.videos[0] === 'string' ? p.videos[0] : p.videos[0].url) : undefined),
    shortVideo: p.shortVideo || (p.videoUrl ? { url: p.videoUrl, title: 'Vídeo Curto', duration: '0:25' } : (Array.isArray(p.videos) && p.videos[0] ? (typeof p.videos[0] === 'string' ? { url: p.videos[0], title: 'Vídeo' } : p.videos[0]) : undefined)),
    category: p.category || 'Geral',
    categorySlug: p.categorySlug || 'geral',
    condition: p.condition || 'novo',
    brand: p.brand || 'Nusali',
    model: p.model || '',
    rating: typeof p.rating === 'number' ? p.rating : 4.8,
    reviewsCount: typeof p.reviewsCount === 'number' ? p.reviewsCount : 12,
    seller: {
      id: p.seller?.id || p.sellerId || 'seller_001',
      name: p.seller?.name || p.sellerName || p.brand || 'Vendedor Oficial Nusali',
      reputationLevel: p.seller?.reputationLevel || 'platinum',
      reputationScore: p.seller?.reputationScore || 4.9,
      salesCount: p.seller?.salesCount || 150,
      isOfficialStore: p.seller?.isOfficialStore !== false,
      location: p.seller?.location || { city: 'Bissau', state: 'Setor Autónomo' },
      goodService: p.seller?.goodService !== false,
      onTimeDelivery: p.seller?.onTimeDelivery !== false,
      country: p.seller?.country || 'GW',
      kycStatus: p.seller?.kycStatus || 'verified',
    },
    storeId: p.storeId || 'store_001',
    storeName: p.storeName || p.seller?.name || 'Vendedor Oficial Nusali',
    isDigitalProduct: Boolean(p.isDigitalProduct),
    weightKg: typeof p.weightKg === 'number' ? p.weightKg : (p.specs?.Peso ? parseFloat(p.specs.Peso.replace(/[^\d.]/g, '')) || 0.5 : 0.5),
    dimensionsCm: p.dimensionsCm || { length: 20, width: 15, height: 10 },
    publishingScope: p.publishingScope || (p.shipping?.isInternational ? 'international' : 'national'),
    targetCountries: Array.isArray(p.targetCountries) && p.targetCountries.length > 0
      ? p.targetCountries
      : (p.shipping?.targetCountries || ['GW', 'PT', 'BR', 'AO', 'US', 'MZ', 'CV', 'ST']),
    originCountry: p.originCountry || p.shipping?.originCountry || p.seller?.country || 'GW',
    productKits: Array.isArray(p.productKits) ? p.productKits : [],
    availableColors: Array.isArray(p.availableColors) ? p.availableColors : [],
    availableSizes: Array.isArray(p.availableSizes) ? p.availableSizes : [],
    variants: Array.isArray(p.variants) ? p.variants : [],
    shipping: {
      freeShipping: p.shipping?.freeShipping ?? p.freeShipping ?? true,
      arrivesTomorrow: p.shipping?.arrivesTomorrow ?? p.arrivesTomorrow ?? true,
      shippingPrice: p.shipping?.shippingPrice ?? (p.freeShipping ? 0 : 1500),
      fullFulfilled: p.shipping?.fullFulfilled ?? p.full ?? true,
      isInternational: p.shipping?.isInternational ?? (p.publishingScope === 'international' || (p.originCountry && p.originCountry !== 'GW')),
      originCountry: p.shipping?.originCountry || p.originCountry || p.seller?.country || 'GW',
      originCity: p.shipping?.originCity || p.seller?.location?.city || 'Bissau',
      targetCountries: p.shipping?.targetCountries || p.targetCountries || ['GW', 'PT', 'BR', 'AO', 'US', 'MZ', 'CV', 'ST'],
      warehouseName: p.shipping?.warehouseName || 'HUB Central Bissau',
      estimatedDays: p.shipping?.estimatedDays || (p.shipping?.isInternational ? 8 : 2),
      customsDutyEstimate: p.shipping?.customsDutyEstimate || 0,
    },
    stock: typeof p.stock === 'number' ? p.stock : 25,
    salesCount: typeof p.salesCount === 'number' ? p.salesCount : 50,
    description: p.description || 'Produto de alta qualidade disponível no Mercado Nusali.',
    specs: p.specs || {},
    questions: Array.isArray(p.questions) ? p.questions : [],
    reviews: Array.isArray(p.reviews) ? p.reviews : [],
    featured: Boolean(p.featured),
    offerOfDay: Boolean(p.offerOfDay),
    createdAt: p.createdAt || new Date().toISOString(),
  };
}
